<ol class="breadcrumb" >
    <li><a href="/index.php?controller=backend" >Home</a></li>
    <li> Quản Lý Danh Mục Sản Phẩm </li>
</ol>

<div class="container-fluid" >
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Danh Mục Sản Phẩm</h3>
            <div class="box-tools" >
                <?php
                Module\quanlysanpham\Model\btnHtml::btnThemDanhMuc();
                ?>
            </div>
        </div>
        <div class="box-body" >
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th>STT</th>
                        <th>Tên Danh Mục</th>
                        <th>Mô Tả</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($items as $index => $item) {
                        $_item = new \Module\quanlysanpham\Model\DanhMuc($item)
                        ?> 
                        <tr>
                            <th style="width: 150px;" > 

                                <?php
                                echo Module\quanlysanpham\Model\btnHtml::btnSuaDanhMuc($_item->Id);
                                echo Module\quanlysanpham\Model\btnHtml::btnXoaDanhMuc($_item->Id);
                                ?>
                            </th>
                            <th><?php echo $index + 1; ?></th> 
                            <th><?php echo $_item->Name; ?></th>
                            <th><?php echo $_item->des; ?></th>
                        </tr>
                        <?php
                    }
                    ?> 
                </tbody>
            </table> 
            <div class="box-footer" >
                <div  class="d-flex"> 
                    <?php
                    \Model\FormCommon::Select("", "", [10, 20, 50, 100],
                            [
                                "style" => "max-width:150px;",
                                "class" => "form-control",
                                "value" => $pageNumber,
                                "onchange" => "SoDongHienThi(this.value)",
                            ]
                    )->render();
                    ?> 
                    <?php
                    $linkPhanTrang = "/index.php?module=quanlysanpham&controller=danhmuc&action=index&keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                    echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                    ?> 
                </div>
            </div>
        </div>
    </div>    
</div>
<script type="text/javascript" >
    var SoDongHienThi = function (evalue) {
        var linkPhanTrang = '/index.php?module=quanlysanpham&controller=danhmuc&action=index&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>
