<ol class="breadcrumb" >
    <li><a href="/index.php?controller=backend" >Home</a></li>
    <li><a href="/index.php?module=quanlysanpham&controller=danhmuc&action=index" >Quản Lý Danh Mục Sản Phẩm</a></li>
    <li> Thêm Mới </li>
</ol>
<div  class="container-fluid" >
    <form action="" method="post">
        <div class="box box-primary" >
            <div class="box-header" >
                <h3 class="box-title" >Thêm Mới</h3>  
            </div>
            <div class="box-body" >
                <div class="col-md-6" >
                    <div class="row" >
                        <?php
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::Name()->renderHTML();
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::parentsId()->renderHTML();
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::Lang()->renderHTML();
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::title()->renderHTML();
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::keyword()->renderHTML();
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::des()->renderHTML();
                        ?>
                    </div>
 
                </div>
            </div>
            <div class="box-footer" >
                <input type="submit" class="btn btn-success" name="Luu" value="Lưu" />
            </div>
        </div>    
    </form>    
</div>


