<ol class="breadcrumb" >
    <li><a href="/index.php?controller=backend" >Home</a></li>
    <li><a href="/index.php?module=quanlysanpham&controller=danhmuc&action=index" >Quản Lý Danh Mục Sản Phẩm</a></li>
    <li> Sửa </li>
</ol>
<?php
$_item = new \Module\quanlysanpham\Model\DanhMuc($item);
?>
<div  class="container-fluid" >
    <form action="" method="post">
        <div class="box box-primary" >
            <div class="box-header" >
                <h3 class="box-title" >Sửa Danh Mục</h3>  
            </div>
            <div class="box-body" >
                <div class="col-md-6" >
                    <div class="row" >
                        <?php
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::Id($_item->Id)->render();
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::Name($_item->Name)->renderHTML();
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::parentsId($_item->parentsId)->renderHTML();
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::Lang($_item->Lang)->renderHTML();
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::title($_item->title)->renderHTML();
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::keyword($_item->keyword)->renderHTML();
                        Module\quanlysanpham\Model\DanhMuc\FormDanhMuc::des($_item->des)->renderHTML();
                        ?>
                    </div>

                </div>
            </div>
            <div class="box-footer" >
                <input type="submit" class="btn btn-success" name="Luu" value="Lưu" />
            </div>
        </div>    
    </form>    
</div>


