<ol class="breadcrumb" >
    <li><a href="/backend" >Home</a></li>
    <li> Tùy Chọn Bài Viết</li>

</ol>

<div class="container-fluid" >
    <form method="get" action="">
        <div class="form-group d-flex" >  

        </div>

    </form>
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Tỉnh Thành</h3>
            <div class="box-tools" >
                <?php
                echo \Model\Locations::btnThem();
                ?> 
            </div>
        </div>
        <div class="box-body" >
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th>STT</th>
                        <th>Mã </th>
                        <th>Tên</th>
                        <th>Cấp Trực Thuộc</th>
                        <th>Ẩn Hiện</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ($Items) {
                        foreach ($Items as $k => $item) {
                            $_item = new Model\Locations($item);
                            ?>   
                            <tr>
                                <th>
                                    <?php
                                    $_item->btnPut();
                                    $_item->btnDelete();
                                    ?>
                                    <!--<a class="btn btn-danger" >Xóa</a>-->
                                </th> 
                                <th><?php echo $k + 1 ?></th> 
                                <th><?php echo $_item->Id ?></th> 
                                <th><?php echo $_item->Name ?></th> 
                                <th><?php echo $_item->Parents()->Name ?></th> 
                                <th><?php echo $_item->IsPublic ?></th> 
                            </tr>

                            <?php
                        }
                    }
                    ?> 
                </tbody>
            </table>    
        </div>
        <div class="box-footer" >
            <div  class="d-flex"> 
                <?php
                \Model\FormCommon::Select("", "", [10, 20, 50, 100],
                        [
                            "style" => "max-width:150px;",
                            "class" => "form-control",
                            "value" => $pageNumber,
                            "onchange" => "SoDongHienThi(this.value)",
                        ]
                )->render();
                ?> 
                <?php
                $linkPhanTrang = "/baiviet/options/?keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                ?> 
            </div>
        </div>
    </div>    
</div>
<script type="text/javascript" >
    var SoDongHienThi = function (evalue) {
        var linkPhanTrang = '/baiviet/options/?keyword=&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>

