<ol class="breadcrumb" >
    <li><a href="/backend" >Home</a></li>
    <li> Danh Sách Dự Án </li>
</ol>

<div class="container-fluid" >
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Danh Mục Sản Phẩm</h3>
            <div class="box-tools" >
                <?php 
                \Module\baiviet\Model\DuAn\DuAn::btnPost();
                ?>
                
            </div>
        </div>
        <div class="box-body" >
            <table class="table table-bordered">

            </table> 

        </div>
    </div>    
</div>    

