<?php

use Module\baiviet\Model\DuAn\FormDuAn;

$_item = new \Module\baiviet\Model\DuAn\DuAn($Item);
?>
<ol class="breadcrumb" >
    <li><a href="/backend" >Home</a></li>
    <li><a href="/baiviet/duan/" >Quản Lý Dự Án</a></li>
    <li> Sửa Dự Án </li>
</ol>
<div  class="container-fluid" >
    <form action="" method="post">
        <div class="box box-primary" >
            <div class="box-header" >
                <h3 class="box-title" >Thêm Mới</h3>  
            </div>
            <div class="box-body" >
                <div class="col-md-6" >
                    <div class="row" >
                        <?php
                        FormDuAn::Id($_item->Id)->renderHTML();
                        FormDuAn::Name($_item->Name)->renderHTML();
                        FormDuAn::Alias($_item->Alias)->renderHTML();
                        FormDuAn::Tinh($_item->Tinh)->renderHTML();
                        FormDuAn::Huyen($_item->Huyen)->renderHTML();
                        FormDuAn::Xa($_item->Xa)->renderHTML();
                        FormDuAn::DiaChi($_item->DiaChi)->renderHTML();
                        ?>
                    </div>

                </div>  
                <div class="col-md-12" >
                    <?php
                    FormDuAn::Content($_item->Content())->renderHTML();
                    ?>
                </div>
            </div>
            <div class="box-footer" >
                <input type="submit" class="btn btn-success" name="Luu" value="Lưu" />
            </div>
        </div>    
    </form>    
</div>


