<!DOCTYPE html>
<html>

    <!-- Mirrored from kutethemes.com/demo/kuteshop/html/ by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 21 Jul 2015 07:11:25 GMT -->
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="/public/homeshop/assets/lib/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="/public/homeshop/assets/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" type="text/css" href="/public/homeshop/assets/lib/select2/css/select2.min.css" />
        <link rel="stylesheet" type="text/css" href="/public/homeshop/assets/lib/jquery.bxslider/jquery.bxslider.css" />
        <link rel="stylesheet" type="text/css" href="/public/homeshop/assets/lib/owl.carousel/owl.carousel.css" />
        <link rel="stylesheet" type="text/css" href="/public/homeshop/assets/lib/jquery-ui/jquery-ui.css" />
        <link rel="stylesheet" type="text/css" href="/public/homeshop/assets/css/animate.css" />
        <link rel="stylesheet" type="text/css" href="/public/homeshop/assets/css/reset.css" />
        <link rel="stylesheet" type="text/css" href="/public/homeshop/assets/css/style.css" />
        <link rel="stylesheet" type="text/css" href="/public/homeshop/assets/css/responsive.css" />

        <title>Kute shop</title>
    </head>
    <body class="home">
        <!-- TOP BANNER -->
        <div id="top-banner" class="top-banner">
            <div class="bg-overlay"></div>
            <div class="container">
                <h1>Special Offer!</h1>
                <h2>Additional 40% OFF For Men & Women Clothings</h2>
                <span>This offer is for online only 7PM to middnight ends in 30th July 2015</span>
                <span class="btn-close"></span>
            </div>
        </div>
        <!-- HEADER -->
        <div id="header" class="header">
            <div class="top-header">
                <div class="container">
                    <div class="nav-top-links">
                        <a class="first-item" href="#"><img alt="phone" src="/public/homeshop/assets/images/phone.png" />00-62-658-658</a>
                        <a href="#"><img alt="email" src="/public/homeshop/assets/images/email.png" />Contact us today!</a>
                    </div>
                    <div class="currency ">
                        <div class="dropdown">
                            <a class="current-open" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">USD</a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Dollar</a></li>
                                <li><a href="#">Euro</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="language ">
                        <div class="dropdown">
                            <a class="current-open" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                                <img alt="email" src="/public/homeshop/assets/images/fr.jpg" />French

                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#"><img alt="email" src="/public/homeshop/assets/images/en.jpg" />English</a></li>
                                <li><a href="#"><img alt="email" src="/public/homeshop/assets/images/fr.jpg" />French</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="support-link">
                        <a href="#">Services</a>
                        <a href="#">Support</a>
                    </div>

                    <div id="user-info-top" class="user-info pull-right">
                        <div class="dropdown">
                            <a class="current-open" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#"><span>My Account</span></a>
                            <ul class="dropdown-menu mega_dropdown" role="menu">
                                <li><a href="login.html">Login</a></li>
                                <li><a href="#">Compare</a></li>
                                <li><a href="#">Wishlists</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!--/.top-header -->
            <!-- MAIN HEADER -->
            <div class="container main-header">
                <div class="row">
                    <div class="col-xs-12 col-sm-3 logo">
                        <a href="index-2.html"><img alt="Kute Shop" src="/public/homeshop/assets/images/logo.png" /></a>
                    </div>
                    <div class="col-xs-7 col-sm-7 header-search-box">
                        <form action="/index/timkiem/" class="form-inline">
                            <div class="form-group form-category">
                                <select class="select-category">
                                    <option value="2">All Categories</option>
                                    <option value="1">Men</option>
                                    <option value="2">Women</option>
                                </select>
                            </div>
                            <div class="form-group input-serach">
                                <input type="text" name="keyword"  placeholder="Keyword here...">
                            </div>
                            <button type="submit" class="pull-right btn-search"></button>
                        </form>
                    </div>
                    <div id="cart-block" class="col-xs-5 col-sm-2 shopping-cart-box">
                        <a class="cart-link" href="order.html">
                            <span class="title">Shopping cart</span>
                            <span class="total">2 items - 122.38 €</span>
                            <span class="notify notify-left">2</span>
                        </a>
                        <div class="cart-block">
                            <div class="cart-block-content">
                                <h5 class="cart-title">2 Items in my cart</h5>
                                <div class="cart-block-list">
                                    <ul>
                                        <li class="product-info">
                                            <div class="p-left">
                                                <a href="#" class="remove_link"></a>
                                                <a href="#">
                                                    <img class="img-responsive" src="/public/homeshop/assets/data/product-100x122.jpg" alt="p10">
                                                </a>
                                            </div>
                                            <div class="p-right">
                                                <p class="p-name">Donec Ac Tempus</p>
                                                <p class="p-rice">61,19 €</p>
                                                <p>Qty: 1</p>
                                            </div>
                                        </li>
                                        <li class="product-info">
                                            <div class="p-left">
                                                <a href="#" class="remove_link"></a>
                                                <a href="#">
                                                    <img class="img-responsive" src="/public/homeshop/assets/data/product-s5-100x122.jpg" alt="p10">
                                                </a>
                                            </div>
                                            <div class="p-right">
                                                <p class="p-name">Donec Ac Tempus</p>
                                                <p class="p-rice">61,19 €</p>
                                                <p>Qty: 1</p>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div class="toal-cart">
                                    <span>Total</span>
                                    <span class="toal-price pull-right">122.38 €</span>
                                </div>
                                <div class="cart-buttons">
                                    <a href="order.html" class="btn-check-out">Checkout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- END MANIN HEADER -->
            <div id="nav-top-menu" class="nav-top-menu">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-3" id="box-vertical-megamenus">
                            <div class="box-vertical-megamenus">
                                <h4 class="title">
                                    <span class="title-menu">Categories</span>
                                    <span class="btn-open-mobile pull-right home-page"><i class="fa fa-bars"></i></span>
                                </h4>
                                <div class="vertical-menu-content is-home">
                                    <ul class="vertical-menu-list">
                                        <li><a href="#"><img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/1.png">Electronics</a></li>
                                        <li>
                                            <a class="parent" href="#"><img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/2.png">Sports &amp; Outdoors</a>
                                            <div class="vertical-dropdown-menu">
                                                <div class="vertical-groups col-sm-12">
                                                    <div class="mega-group col-sm-4">
                                                        <h4 class="mega-group-header"><span>Tennis</span></h4>
                                                        <ul class="group-link-default">
                                                            <li><a href="#">Tennis</a></li>
                                                            <li><a href="#">Coats &amp; Jackets</a></li>
                                                            <li><a href="#">Blouses &amp; Shirts</a></li>
                                                            <li><a href="#">Tops &amp; Tees</a></li>
                                                            <li><a href="#">Hoodies &amp; Sweatshirts</a></li>
                                                            <li><a href="#">Intimates</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="mega-group col-sm-4">
                                                        <h4 class="mega-group-header"><span>Swimming</span></h4>
                                                        <ul class="group-link-default">
                                                            <li><a href="#">Dresses</a></li>
                                                            <li><a href="#">Coats &amp; Jackets</a></li>
                                                            <li><a href="#">Blouses &amp; Shirts</a></li>
                                                            <li><a href="#">Tops &amp; Tees</a></li>
                                                            <li><a href="#">Hoodies &amp; Sweatshirts</a></li>
                                                            <li><a href="#">Intimates</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="mega-group col-sm-4">
                                                        <h4 class="mega-group-header"><span>Shoes</span></h4>
                                                        <ul class="group-link-default">
                                                            <li><a href="#">Dresses</a></li>
                                                            <li><a href="#">Coats &amp; Jackets</a></li>
                                                            <li><a href="#">Blouses &amp; Shirts</a></li>
                                                            <li><a href="#">Tops &amp; Tees</a></li>
                                                            <li><a href="#">Hoodies &amp; Sweatshirts</a></li>
                                                            <li><a href="#">Intimates</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="mega-custom-html col-sm-12">
                                                        <a href="#"><img src="/public/homeshop/assets/data/banner-megamenu.jpg" alt="Banner"></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li><a href="#"><img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/3.png">Smartphone &amp; Tablets</a></li>
                                        <li><a href="#"><img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/4.png">Health &amp; Beauty Bags</a></li>
                                        <li>
                                            <a class="parent" href="#">
                                                <img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/5.png">Shoes &amp; Accessories</a>
                                            <div class="vertical-dropdown-menu">
                                                <div class="vertical-groups col-sm-12">
                                                    <div class="mega-group col-sm-12">
                                                        <h4 class="mega-group-header"><span>Special products</span></h4>
                                                        <div class="row mega-products">
                                                            <div class="col-sm-3 mega-product">
                                                                <div class="product-avatar">
                                                                    <a href="#"><img src="/public/homeshop/assets/data/p10.jpg" alt="product1"></a>
                                                                </div>
                                                                <div class="product-name">
                                                                    <a href="#">Fashion hand bag</a>
                                                                </div>
                                                                <div class="product-price">
                                                                    <div class="new-price">$38</div>
                                                                    <div class="old-price">$45</div>
                                                                </div>
                                                                <div class="product-star">
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star-half-o"></i>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-3 mega-product">
                                                                <div class="product-avatar">
                                                                    <a href="#"><img src="/public/homeshop/assets/data/p11.jpg" alt="product1"></a>
                                                                </div>
                                                                <div class="product-name">
                                                                    <a href="#">Fashion hand bag</a>
                                                                </div>
                                                                <div class="product-price">
                                                                    <div class="new-price">$38</div>
                                                                    <div class="old-price">$45</div>
                                                                </div>
                                                                <div class="product-star">
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star-half-o"></i>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-3 mega-product">
                                                                <div class="product-avatar">
                                                                    <a href="#"><img src="/public/homeshop/assets/data/p12.jpg" alt="product1"></a>
                                                                </div>
                                                                <div class="product-name">
                                                                    <a href="#">Fashion hand bag</a>
                                                                </div>
                                                                <div class="product-price">
                                                                    <div class="new-price">$38</div>
                                                                    <div class="old-price">$45</div>
                                                                </div>
                                                                <div class="product-star">
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star-half-o"></i>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-3 mega-product">
                                                                <div class="product-avatar">
                                                                    <a href="#"><img src="/public/homeshop/assets/data/p13.jpg" alt="product1"></a>
                                                                </div>
                                                                <div class="product-name">
                                                                    <a href="#">Fashion hand bag</a>
                                                                </div>
                                                                <div class="product-price">
                                                                    <div class="new-price">$38</div>
                                                                    <div class="old-price">$45</div>
                                                                </div>
                                                                <div class="product-star">
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star"></i>
                                                                    <i class="fa fa-star-half-o"></i>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li><a href="#"><img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/6.png">Toys &amp; Hobbies</a></li>
                                        <li><a href="#"><img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/7.png">Computers &amp; Networking</a></li>
                                        <li><a href="#"><img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/8.png">Laptops &amp; Accessories</a></li>
                                        <li><a href="#"><img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/9.png">Jewelry &amp; Watches</a></li>
                                        <li><a href="#"><img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/10.png">Flashlights &amp; Lamps</a></li>
                                        <li>
                                            <a href="#">
                                                <img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/11.png">
                                                Cameras &amp; Photo
                                            </a>
                                        </li>
                                        <li class="cat-link-orther">
                                            <a href="#">
                                                <img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/5.png">
                                                Television
                                            </a>
                                        </li>
                                        <li class="cat-link-orther">
                                            <a href="#">
                                                <img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/7.png">Computers &amp; Networking
                                            </a>
                                        </li>
                                        <li class="cat-link-orther">
                                            <a href="#">
                                                <img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/6.png">
                                                Toys &amp; Hobbies
                                            </a>
                                        </li>
                                        <li class="cat-link-orther">
                                            <a href="#"><img class="icon-menu" alt="Funky roots" src="/public/homeshop/assets/data/9.png">Jewelry &amp; Watches</a></li>
                                    </ul>
                                    <div class="all-category"><span class="open-cate">All Categories</span></div>
                                </div>
                            </div>
                        </div>
                        <div id="main-menu" class="col-sm-9 main-menu">
                            <nav class="navbar navbar-default">
                                <div class="container-fluid">
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                            <i class="fa fa-bars"></i>
                                        </button>
                                        <a class="navbar-brand" href="#">MENU</a>
                                    </div>
                                    <div id="navbar" class="navbar-collapse collapse">
                                        <ul class="nav navbar-nav">
                                            <li class="active"><a href="#">Home</a></li>
                                            <li class="dropdown">
                                                <a href="category.html" class="dropdown-toggle" data-toggle="dropdown">Fashion</a>
                                                <ul class="dropdown-menu mega_dropdown" role="menu" style="width: 830px;">
                                                    <li class="block-container col-sm-3">
                                                        <ul class="block">
                                                            <li class="img_container">
                                                                <a href="#">
                                                                    <img class="img-responsive" src="/public/homeshop/assets/data/men.png" alt="sport">
                                                                </a>
                                                            </li>
                                                            <li class="link_container group_header">
                                                                <a href="#">MEN'S</a>
                                                            </li>
                                                            <li class="link_container"><a href="#">Skirts</a></li>
                                                            <li class="link_container"><a href="#">Jackets</a></li>
                                                            <li class="link_container"><a href="#">Tops</a></li>
                                                            <li class="link_container"><a href="#">Scarves</a></li>
                                                            <li class="link_container"><a href="#">Pants</a></li>
                                                        </ul>
                                                    </li>
                                                    <li class="block-container col-sm-3">
                                                        <ul class="block">
                                                            <li class="img_container">
                                                                <a href="#">
                                                                    <img class="img-responsive" src="/public/homeshop/assets/data/women.png" alt="sport">
                                                                </a>
                                                            </li>
                                                            <li class="link_container group_header">
                                                                <a href="#">WOMEN'S</a>
                                                            </li>
                                                            <li class="link_container"><a href="#">Skirts</a></li>
                                                            <li class="link_container"><a href="#">Jackets</a></li>
                                                            <li class="link_container"><a href="#">Tops</a></li>
                                                            <li class="link_container"><a href="#">Scarves</a></li>
                                                            <li class="link_container"><a href="#">Pants</a></li>
                                                        </ul>
                                                    </li>
                                                    <li class="block-container col-sm-3">
                                                        <ul class="block">
                                                            <li class="img_container">
                                                                <a href="#">
                                                                    <img class="img-responsive" src="/public/homeshop/assets/data/kid.png" alt="sport">
                                                                </a>
                                                            </li>
                                                            <li class="link_container group_header">
                                                                <a href="#">Kids</a>
                                                            </li>
                                                            <li class="link_container"><a href="#">Shoes</a></li>
                                                            <li class="link_container"><a href="#">Clothing</a></li>
                                                            <li class="link_container"><a href="#">Tops</a></li>
                                                            <li class="link_container"><a href="#">Scarves</a></li>
                                                            <li class="link_container"><a href="#">Accessories</a></li>
                                                        </ul>
                                                    </li>
                                                    <li class="block-container col-sm-3">
                                                        <ul class="block">
                                                            <li class="img_container">
                                                                <a href="#">
                                                                    <img class="img-responsive" src="/public/homeshop/assets/data/trending.png" alt="sport">
                                                                </a>
                                                            </li>
                                                            <li class="link_container group_header">
                                                                <a href="#">TRENDING</a>
                                                            </li>
                                                            <li class="link_container"><a href="#">Men's Clothing</a></li>
                                                            <li class="link_container"><a href="#">Kid's Clothing</a></li>
                                                            <li class="link_container"><a href="#">Women's Clothing</a></li>
                                                            <li class="link_container"><a href="#">Accessories</a></li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li><a href="category.html" class="dropdown-toggle" data-toggle="dropdown">Sports</a></li>
                                            <li class="dropdown">
                                                <a href="category.html" class="dropdown-toggle" data-toggle="dropdown">Foods</a>
                                                <ul class="mega_dropdown dropdown-menu" style="width: 830px;">
                                                    <li class="block-container col-sm-3">
                                                        <ul class="block">
                                                            <li class="link_container group_header">
                                                                <a href="#">Asian</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Vietnamese Pho</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Noodles</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Seafood</a>
                                                            </li>
                                                            <li class="link_container group_header">
                                                                <a href="#">Sausages</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Meat Dishes</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Desserts</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Tops</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Tops</a>
                                                            </li>
                                                        </ul>
                                                    </li>
                                                    <li class="block-container col-sm-3">
                                                        <ul class="block">
                                                            <li class="link_container group_header">
                                                                <a href="#">European</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Greek Potatoes</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Famous Spaghetti</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Famous Spaghetti</a>
                                                            </li>
                                                            <li class="link_container group_header">
                                                                <a href="#">Chicken</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Italian Pizza</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">French Cakes</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Tops</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Tops</a>
                                                            </li>
                                                        </ul>
                                                    </li>
                                                    <li class="block-container col-sm-3">
                                                        <ul class="block">
                                                            <li class="link_container group_header">
                                                                <a href="#">FAST</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Hamberger</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Pizza</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Noodles</a>
                                                            </li>
                                                            <li class="link_container group_header">
                                                                <a href="#">Sandwich</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Salad</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Paste</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Tops</a>
                                                            </li>
                                                            <li class="link_container">
                                                                <a href="#">Tops</a>
                                                            </li>
                                                        </ul>
                                                    </li>
                                                    <li class="block-container col-sm-3">
                                                        <ul class="block">
                                                            <li class="img_container">
                                                                <img src="/public/homeshop/assets/data/banner-topmenu.jpg" alt="Banner">
                                                            </li>
                                                        </ul>
                                                    </li>

                                                </ul>
                                            </li>
                                            <li class="dropdown">
                                                <a href="category.html" class="dropdown-toggle" data-toggle="dropdown">Digital</a>
                                                <ul class="dropdown-menu container-fluid">
                                                    <li class="block-container">
                                                        <ul class="block">
                                                            <li class="link_container"><a href="#">Mobile</a></li>
                                                            <li class="link_container"><a href="#">Tablets</a></li>
                                                            <li class="link_container"><a href="#">Laptop</a></li>
                                                            <li class="link_container"><a href="#">Memory Cards</a></li>
                                                            <li class="link_container"><a href="#">Accessories</a></li>
                                                        </ul>
                                                    </li>
                                                </ul> 
                                            </li>
                                            <li><a href="category.html">Furniture</a></li>
                                            <li><a href="category.html">Jewelry</a></li>
                                            <li><a href="category.html">Blog</a></li>
                                        </ul>
                                    </div><!--/.nav-collapse -->
                                </div>
                            </nav>
                        </div>
                    </div>
                    <!-- userinfo on top-->
                    <div id="form-search-opntop">
                    </div>
                    <!-- userinfo on top-->
                    <div id="user-info-opntop">
                    </div>
                    <!-- CART ICON ON MMENU -->
                    <div id="shopping-cart-box-ontop">
                        <i class="fa fa-shopping-cart"></i>
                        <div class="shopping-cart-box-ontop-content"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end header -->
        <!-- Home slideder-->
        <?php 
        \Views\theme\homeshop\Functions::Slider();
        
        ?>
        
        <!-- END Home slideder-->
        <!-- servives -->
        <div class="container">
            <div class="service ">
                <div class="col-xs-6 col-sm-3 service-item">
                    <div class="icon">
                        <img alt="services" src="/public/homeshop/assets/data/s1.png" />
                    </div>
                    <div class="info">
                        <a href="#"><h3>Free Shipping</h3></a>
                        <span>On order over $200</span>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3 service-item">
                    <div class="icon">
                        <img alt="services" src="/public/homeshop/assets/data/s2.png" />
                    </div>
                    <div class="info">
                        <a href="#"><h3>30-day return</h3></a>
                        <span>Moneyback guarantee</span>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3 service-item">
                    <div class="icon">
                        <img alt="services" src="/public/homeshop/assets/data/s3.png" />
                    </div>

                    <div class="info" >
                        <a href="#"><h3>24/7 support</h3></a>
                        <span>Online consultations</span>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3 service-item">
                    <div class="icon">
                        <img alt="services" src="/public/homeshop/assets/data/s4.png" />
                    </div>
                    <div class="info">
                        <a href="#"><h3>SAFE SHOPPING</h3></a>
                        <span>Safe Shopping Guarantee</span>
                    </div>
                </div>
            </div>
        </div>
        <!-- end services -->
        <?php 
        include $_Content;
        ?>

        <div class="container">
            <div class="brand-showcase">
                <h2 class="brand-showcase-title">
                    brand showcase
                </h2>
                <div class="brand-showcase-box">
                    <ul class="brand-showcase-logo owl-carousel" data-loop="true" data-nav = "true" data-dots="false" data-margin = "1" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":2},"600":{"items":5},"1000":{"items":8}}'>
                        <li data-tab="showcase-1" class="item active"><img src="/public/homeshop/assets/data/gucci.png" alt="logo" class="item-img" /></li>
                        <li data-tab="showcase-2" class="item"><img src="/public/homeshop/assets/data/gucci.png" alt="logo" class="item-img" /></li>
                        <li data-tab="showcase-3" class="item"><img src="/public/homeshop/assets/data/gucci.png" alt="logo" class="item-img" /></li>
                        <li data-tab="showcase-4" class="item"><img src="/public/homeshop/assets/data/gucci.png" alt="logo" class="item-img" /></li>
                        <li data-tab="showcase-5" class="item"><img src="/public/homeshop/assets/data/gucci.png" alt="logo" class="item-img" /></li>
                        <li data-tab="showcase-6" class="item"><img src="/public/homeshop/assets/data/gucci.png" alt="logo" class="item-img" /></li>
                        <li data-tab="showcase-7" class="item"><img src="/public/homeshop/assets/data/gucci.png" alt="logo" class="item-img" /></li>
                        <li data-tab="showcase-8" class="item"><img src="/public/homeshop/assets/data/gucci.png" alt="logo" class="item-img" /></li>
                        <li data-tab="showcase-9" class="item"><img src="/public/homeshop/assets/data/gucci.png" alt="logo" class="item-img" /></li>
                    </ul>
                    <div class="brand-showcase-content">
                        <div class="brand-showcase-content-tab active" id="showcase-1">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4 trademark-info">
                                    <div class="trademark-logo">
                                        <a href="#"><img src="/public/homeshop/assets/data/trademark.jpg" alt="trademark"></a>
                                    </div>
                                    <div class="trademark-desc">
                                        Whatever the occasion, complete your outfit with one of Hermes Fashion’s stylish women’s bags. Discover our spring collection.
                                    </div>
                                    <a href="#" class="trademark-link">shop this brand</a>
                                </div>
                                <div class="col-xs-12 col-sm-8 trademark-product">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-repon" src="/public/homeshop/assets/data/p24.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p25.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p26.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p27.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="brand-showcase-content-tab" id="showcase-2">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4 trademark-info">
                                    <div class="trademark-logo">
                                        <a href="#"><img src="/public/homeshop/assets/data/trademark.jpg" alt="trademark"></a>
                                    </div>
                                    <div class="trademark-desc">
                                        Whatever the occasion, complete your outfit with one of Hermes Fashion’s stylish women’s bags. Discover our spring collection.
                                    </div>
                                    <a href="#" class="trademark-link">shop this brand</a>
                                </div>
                                <div class="col-xs-12 col-sm-8 trademark-product">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-repon" src="/public/homeshop/assets/data/p10.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p11.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p12.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p13.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="brand-showcase-content-tab" id="showcase-3">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4 trademark-info">
                                    <div class="trademark-logo">
                                        <a href="#"><img src="/public/homeshop/assets/data/trademark.jpg" alt="trademark"></a>
                                    </div>
                                    <div class="trademark-desc">
                                        Whatever the occasion, complete your outfit with one of Hermes Fashion’s stylish women’s bags. Discover our spring collection.
                                    </div>
                                    <a href="#" class="trademark-link">shop this brand</a>
                                </div>
                                <div class="col-xs-12 col-sm-8 trademark-product">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-repon" src="/public/homeshop/assets/data/p14.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p15.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p16.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p17.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="brand-showcase-content-tab" id="showcase-4">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4 trademark-info">
                                    <div class="trademark-logo">
                                        <a href="#"><img src="/public/homeshop/assets/data/trademark.jpg" alt="trademark"></a>
                                    </div>
                                    <div class="trademark-desc">
                                        Whatever the occasion, complete your outfit with one of Hermes Fashion’s stylish women’s bags. Discover our spring collection.
                                    </div>
                                    <a href="#" class="trademark-link">shop this brand</a>
                                </div>
                                <div class="col-xs-12 col-sm-8 trademark-product">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-repon" src="/public/homeshop/assets/data/p18.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p19.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p20.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p21.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="brand-showcase-content-tab" id="showcase-5">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4 trademark-info">
                                    <div class="trademark-logo">
                                        <a href="#"><img src="/public/homeshop/assets/data/trademark.jpg" alt="trademark"></a>
                                    </div>
                                    <div class="trademark-desc">
                                        Whatever the occasion, complete your outfit with one of Hermes Fashion’s stylish women’s bags. Discover our spring collection.
                                    </div>
                                    <a href="#" class="trademark-link">shop this brand</a>
                                </div>
                                <div class="col-xs-12 col-sm-8 trademark-product">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-repon" src="/public/homeshop/assets/data/p22.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p23.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p24.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p25.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="brand-showcase-content-tab" id="showcase-6">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4 trademark-info">
                                    <div class="trademark-logo">
                                        <a href="#"><img src="/public/homeshop/assets/data/trademark.jpg" alt="trademark"></a>
                                    </div>
                                    <div class="trademark-desc">
                                        Whatever the occasion, complete your outfit with one of Hermes Fashion’s stylish women’s bags. Discover our spring collection.
                                    </div>
                                    <a href="#" class="trademark-link">shop this brand</a>
                                </div>
                                <div class="col-xs-12 col-sm-8 trademark-product">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-repon" src="/public/homeshop/assets/data/p26.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p27.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p28.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p29.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="brand-showcase-content-tab" id="showcase-7">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4 trademark-info">
                                    <div class="trademark-logo">
                                        <a href="#"><img src="/public/homeshop/assets/data/trademark.jpg" alt="trademark"></a>
                                    </div>
                                    <div class="trademark-desc">
                                        Whatever the occasion, complete your outfit with one of Hermes Fashion’s stylish women’s bags. Discover our spring collection.
                                    </div>
                                    <a href="#" class="trademark-link">shop this brand</a>
                                </div>
                                <div class="col-xs-12 col-sm-8 trademark-product">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-repon" src="/public/homeshop/assets/data/p30.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p31.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p32.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p15.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="brand-showcase-content-tab" id="showcase-8">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4 trademark-info">
                                    <div class="trademark-logo">
                                        <a href="#"><img src="/public/homeshop/assets/data/trademark.jpg" alt="trademark"></a>
                                    </div>
                                    <div class="trademark-desc">
                                        Whatever the occasion, complete your outfit with one of Hermes Fashion’s stylish women’s bags. Discover our spring collection.
                                    </div>
                                    <a href="#" class="trademark-link">shop this brand</a>
                                </div>
                                <div class="col-xs-12 col-sm-8 trademark-product">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-repon" src="/public/homeshop/assets/data/p25.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p21.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p10.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p23.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="brand-showcase-content-tab" id="showcase-9">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4 trademark-info">
                                    <div class="trademark-logo">
                                        <a href="#"><img src="/public/homeshop/assets/data/trademark.jpg" alt="trademark"></a>
                                    </div>
                                    <div class="trademark-desc">
                                        Whatever the occasion, complete your outfit with one of Hermes Fashion’s stylish women’s bags. Discover our spring collection.
                                    </div>
                                    <a href="#" class="trademark-link">shop this brand</a>
                                </div>
                                <div class="col-xs-12 col-sm-8 trademark-product">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-repon" src="/public/homeshop/assets/data/p24.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p14.jpg" alt=""></a>
                                            </div>
                                            <div class="image-product hover-zoom">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p30.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 product-item">
                                            <div class="image-product hover-zoom">
                                                <a href="#"><img class="img-responsive" src="/public/homeshop/assets/data/p29.jpg" alt=""></a>
                                            </div>
                                            <div class="info-product">
                                                <a href="#">
                                                    <h5>Maecenas consequat mauris</h5>
                                                </a>
                                                <span class="product-price">$38.87</span>
                                                <div class="product-star">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                <a class="btn-view-more" title="View More" href="#">View More</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div id="content-wrap">
            <div class="container">
                <div id="hot-categories" class="row">
                    <div class="col-sm-12 group-title-box">
                        <h2 class="group-title ">
                            <span>Hot categories</span>
                        </h2>
                    </div>

                    <div class="col-sm-6  col-lg-3 cate-box">
                        <div class="cate-tit" >
                            <div class="div-1" style="width: 46%;">
                                <div class="cate-name-wrap">
                                    <p class="cate-name">Electronics</p>
                                </div>
                                <a href="#" class="cate-link link-active" data-ac="flipInX" ><span>shop now</span></a>
                            </div>
                            <div class="div-2" >
                                <a href="#">
                                    <img src="/public/homeshop/assets/data/cate-product1.png" alt="Electronics" class="hot-cate-img" />
                                </a>
                            </div>

                        </div>
                        <div class="cate-content">
                            <ul>
                                <li><a href="#">Batteries & Chargers</a></li>
                                <li><a href="#">Headphone, Headset</a></li>
                                <li><a href="#">Home Audio</a></li>
                                <li><a href="#">Mp3 Player Accessories</a></li>
                            </ul>
                        </div>
                    </div> <!-- /.cate-box -->

                    <div class="col-sm-6  col-lg-3 cate-box">
                        <div class="cate-tit" >
                            <div class="div-1" style="width: 46%;">
                                <div class="cate-name-wrap">
                                    <p class="cate-name">Sport & Outdoors</p>
                                </div>
                                <a href="#" class="cate-link" data-ac="flipInX" ><span>shop now</span></a>
                            </div>
                            <div class="div-2" >
                                <a href="#">
                                    <img src="/public/homeshop/assets/data/cate-product2.png" alt="Electronics" class="hot-cate-img" />
                                </a>
                            </div>
                        </div>
                        <div class="cate-content">
                            <ul>
                                <li><a href="#">Golf Supplies</a></li>
                                <li><a href="#">Outdoor & Traveling Supplies</a></li>
                                <li><a href="#">Camping & Hiking</a></li>
                                <li><a href="#">Fishing</a></li>
                            </ul>
                        </div>
                    </div> <!-- /.cate-box -->
                    <div class="col-sm-6  col-lg-3 cate-box">
                        <div class="cate-tit" >
                            <div class="div-1" style="width: 46%;">
                                <div class="cate-name-wrap">
                                    <p class="cate-name">Fashion</p>
                                </div>
                                <a href="#" class="cate-link" data-ac="flipInX" ><span>shop now</span></a>
                            </div>
                            <div class="div-2" >
                                <a href="#">
                                    <img src="/public/homeshop/assets/data/cate-product3.png" alt="Electronics" class="hot-cate-img"/>
                                </a>
                            </div>

                        </div>
                        <div class="cate-content">
                            <ul>
                                <li><a href="#">Batteries & Chargers</a></li>
                                <li><a href="#">Headphone, Headset</a></li>
                                <li><a href="#">Home Audio</a></li>
                                <li><a href="#">Mp3 Player Accessories</a></li>
                            </ul>
                        </div>
                    </div> <!-- /.cate-box -->
                    <div class="col-sm-6  col-lg-3 cate-box">
                        <div class="cate-tit" >
                            <div class="div-1" style="width: 46%;">
                                <div class="cate-name-wrap">
                                    <p class="cate-name">Health & Beauty</p>
                                </div>
                                <a href="#" class="cate-link" data-ac="flipInX" ><span>shop now</span></a>
                            </div>
                            <div class="div-2" >
                                <a href="#">
                                    <img src="/public/homeshop/assets/data/cate-product4.png" alt="Electronics" class="hot-cate-img" />
                                </a>
                            </div>

                        </div>
                        <div class="cate-content">
                            <ul>
                                <li><a href="#">Bath & Body</a></li>
                                <li><a href="#">Shaving & Hair Removal</a></li>
                                <li><a href="#">Fragrances</a></li>
                                <li><a href="#">Salon & Spa Equipment</a></li>
                            </ul>
                        </div>
                    </div> <!-- /.cate-box -->
                    <div class="col-sm-6  col-lg-3 cate-box">
                        <div class="cate-tit" >
                            <div class="div-1" style="width: 46%;">
                                <div class="cate-name-wrap">
                                    <p class="cate-name">Jewelry & Watches</p>
                                </div>
                                <a href="#" class="cate-link" data-ac="flipInX" ><span>shop now</span></a>
                            </div>
                            <div class="div-2" >
                                <a href="#">
                                    <img src="/public/homeshop/assets/data/cate-product5.png" alt="Electronics" class="hot-cate-img" />
                                </a>
                            </div>
                        </div>
                        <div class="cate-content">
                            <ul>
                                <li><a href="#">Men Watches</a></li>
                                <li><a href="#">Wedding Rings</a></li>
                                <li><a href="#">Earring</a></li>
                                <li><a href="#">Necklaces</a></li>
                            </ul>
                        </div>
                    </div> <!-- /.cate-box -->

                    <div class="col-sm-6  col-lg-3 cate-box">
                        <div class="cate-tit" >
                            <div class="div-1" style="width: 46%;">
                                <div class="cate-name-wrap">
                                    <p class="cate-name">Digital</p>
                                </div>
                                <a href="#" class="cate-link" data-ac="flipInX" ><span>shop now</span></a>
                            </div>
                            <div class="div-2" >
                                <a href="#">
                                    <img src="/public/homeshop/assets/data/cate-product6.png" alt="Electronics" class="hot-cate-img" />
                                </a>
                            </div>
                        </div>
                        <div class="cate-content">
                            <ul>
                                <li><a href="#">Accessories for iPhone</a></li>
                                <li><a href="#">Accessories for iPad</a></li>
                                <li><a href="#">Accessories for Tablet PC</a></li>
                                <li><a href="#">Tablet PC</a></li>
                            </ul>
                        </div>
                    </div><!-- /.cate-box -->
                    <div class="col-sm-6  col-lg-3 cate-box">
                        <div class="cate-tit" >
                            <div class="div-1" style="width: 46%;">
                                <div class="cate-name-wrap">
                                    <p class="cate-name">Furniture</p>
                                </div>
                                <a href="#" class="cate-link" data-ac="flipInX" ><span>shop now</span></a>
                            </div>
                            <div class="div-2" >
                                <a href="#">
                                    <img src="/public/homeshop/assets/data/cate-product7.png" alt="Electronics" class="hot-cate-img" />
                                </a>
                            </div>

                        </div>
                        <div class="cate-content">
                            <ul>
                                <li><a href="#">Batteries & Chargers</a></li>
                                <li><a href="#">Headphone, Headset</a></li>
                                <li><a href="#">Home Audio</a></li>
                                <li><a href="#">Mp3 Player Accessories</a></li>
                            </ul>
                        </div>
                    </div> <!-- /.cate-box -->
                    <div class="col-sm-6  col-lg-3 cate-box">
                        <div class="cate-tit" >
                            <div class="div-1" style="width: 46%;">
                                <div class="cate-name-wrap">
                                    <p class="cate-name">Toys & Hobbies</p>
                                </div>
                                <a href="#" class="cate-link" data-ac="flipInX" ><span>shop now</span></a>
                            </div>
                            <div class="div-2" >
                                <a href="#">
                                    <img src="/public/homeshop/assets/data/cate-product8.png" alt="Electronics" class="hot-cate-img" />
                                </a>
                            </div>
                        </div>
                        <div class="cate-content">
                            <ul>
                                <li><a href="#">Walkera</a></li>
                                <li><a href="#">Fpv System & Parts</a></li>
                                <li><a href="#">RC Cars & Parts</a></li>
                                <li><a href="#">Helicopters & Part</a></li>
                            </ul>
                        </div>
                    </div><!-- /.cate-box -->                                                       
                </div> <!-- /#hot-categories -->

            </div> <!-- /.container -->
        </div>

        <!-- Footer -->
        <footer class="ajaxHtml" data-target="#footer" data-url="/ajaxhtml/footer/" id="footer">
            
        </footer>
        <a href="#" class="scroll_top" title="Scroll to Top" style="display: inline;">Scroll</a>
        <!-- Script-->
        <script type="text/javascript" src="/public/homeshop/assets/lib/jquery/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" src="/public/homeshop/assets/lib/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/public/homeshop/assets/lib/select2/js/select2.min.js"></script>
        <script type="text/javascript" src="/public/homeshop/assets/lib/jquery.bxslider/jquery.bxslider.min.js"></script>
        <script type="text/javascript" src="/public/homeshop/assets/lib/owl.carousel/owl.carousel.min.js"></script>
        <script type="text/javascript" src="/public/homeshop/assets/lib/jquery.countdown/jquery.countdown.min.js"></script>
        <script type="text/javascript" src="/public/homeshop/assets/js/jquery.actual.min.js"></script>
        <script type="text/javascript" src="/public/homeshop/assets/js/theme-script.js"></script>
        
        <script src="/public/Common.js" type="text/javascript"></script>
    </body>
</html>