<ol class="breadcrumb" >
    <li><a href="/index.php?controller=backend" >Home</a></li>
    <li><a href="/index.php?module=quanlysanpham&controller=sanpham&action=index" >Danh Sách Sản Phẩm</a></li>
    <li> Thêm Mới </li>
</ol>
<?php 
use Module\quanlysanpham\Model\SanPham\FormSanPham;
?>
<div  class="container-fluid" >
    <form action="" method="post">
        <div class="box box-primary" >
            <div class="box-header" >
                <h3 class="box-title" >Thêm Mới</h3>  
            </div>
            <div class="box-body" >
                <div class="col-md-6" >
                    <div class="row" >
                        <?php
                            FormSanPham::Name()->renderHTML();
                            FormSanPham::DanhMucId()->renderHTML();
                            FormSanPham::Des()->renderHTML();
                            FormSanPham::Title()->renderHTML();
                            FormSanPham::Keyword()->renderHTML();
                        ?>
                    </div>

                </div>
            </div>
            <div class="box-footer" >
                <input type="submit" class="btn btn-success" name="Luu" value="Lưu" />
            </div>
        </div>    
    </form>    
</div>
