<ol class="breadcrumb" >
    <li><a href="/index.php?controller=backend" >Home</a></li>
    <li><a href="/index.php?module=quanlysanpham&controller=sanpham&action=index" >Danh Sách Sản Phẩm</a></li>
    <li> Sửa </li>
</ol>
<?php

use Module\quanlysanpham\Model\SanPham\FormSanPham;

$_item = new Module\quanlysanpham\Model\SanPham($item);
?>
<div  class="container-fluid" >
    <form action="" method="post">
        <div class="box box-primary" > 
            <div class="box-header" >
                <div class="box-tools" >
                    <button type="submit" class="btn btn-success" name="Luu" value="Lưu" >Lưu</button>
                </div>
            </div>
            <div class="box-body" >
                <div class="col-md-9" >

                    <?php
                    FormSanPham::Id($_item->Id)->render();
                    FormSanPham::Name($_item->Name)->renderHTML();
                    ?>
                    <div class="form-group" >
                        <label>Perlink</label>
                        <div class="d-flex" >
                            <?php
                            FormSanPham::Alias($_item->Alias)->render();
                            ?>
                            <label class="btn btn-primary">
                                <input checked value="1" name="KhoaAlias" type="checkbox" >
                                Khóa
                            </label>
                        </div>
                    </div>


                    <div class="row" >
                        <div class="col-md-4" >
                            <?php
                            FormSanPham::Price($_item->Price)->renderHTML();
                            ?>
                        </div>
                        <div class="col-md-4" >
                            <?php
                            FormSanPham::oldPrice($_item->oldPrice)->renderHTML();
                            ?>
                        </div>
                        <div class="col-md-4" >
                            <?php
                            FormSanPham::Number($_item->Number)->renderHTML();
                            ?>
                        </div>
                    </div>
                    <div role="tabpanel">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active">
                                <a href="#MoTa" aria-controls="MoTa" role="tab" data-toggle="tab">Mô Tả Ngắn</a>
                            </li>
                            <li role="presentation">
                                <a href="#Content" aria-controls="Content" role="tab" data-toggle="tab">Mô Tả Sản Phẩm</a>
                            </li>
                            <li role="presentation">
                                <a href="#SEO" aria-controls="SEO" role="tab" data-toggle="tab">SEO</a>
                            </li>
                            <li role="presentation">
                                <a href="#ThuocTinh" aria-controls="Other" role="tab" data-toggle="tab">Thuộc Tính</a>
                            </li>
                            <li role="presentation">
                                <a href="#Other" aria-controls="Other" role="tab" data-toggle="tab">Khác</a>
                            </li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane  " id="ThuocTinh">
                                <!--danh sach thuoc tinh sản phẩm--> 
                                <div class="list-group" >

                                    <?php
                                    $SPTT = new Module\quanlysanpham\Model\SanPhamThuocTinh();
                                    $itemTT = $SPTT->GetItems("", 1, 1000, $total);
                                    foreach ($itemTT as $value) {
                                        ?> 
                                        <div class="list-group-item" >
                                            <label>
                                                <input  type="checkbox" >
                                                <?php echo $value["Name"]; ?>
                                            </label>
                                        </div>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane active" id="MoTa">
                                <?php
                                FormSanPham::Summary($_item->Summary)->renderHTML()
                                ?>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="Other">
                                <?php
                                FormSanPham::BuyTimes($_item->BuyTimes)->renderHTML();
                                FormSanPham::Views($_item->Views)->renderHTML();
                                ?>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="Content">
                                <?php
                                FormSanPham::Content($_item->Content())->renderHTML()
                                ?>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="SEO">
                                <div class="row" >
                                    <div  class="col-md-4"><?php FormSanPham::Title($_item->Title)->renderHTML(); ?></div>
                                    <div  class="col-md-4"><?php FormSanPham::Des($_item->Des)->renderHTML(); ?></div>
                                    <div  class="col-md-4"><?php FormSanPham::Keyword($_item->Keyword)->renderHTML(); ?></div>
                                </div>  
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3" >

                    <?php
                    FormSanPham::DanhMucId($_item->DanhMucId)->renderHTML();
                    FormSanPham::isShow($_item->isShow)->renderHTML();
                    FormSanPham::STT($_item->STT)->renderHTML();
                    FormSanPham::Lang($_item->Lang)->renderHTML();
                    ?>
                    <label style="border: dashed 2px green;display: block;width: 100%;height: 100px;overflow: hidden" >
                        <img id="imgHinhDaiDien" style="min-height: 100px;height: 100px" src="<?php echo $_item->UrlImages ?>" >
                        Chọn Hình Đại Diện
                        <button style="display: none" type="button" onclick="BrowseServer('UrlImages', 'imgHinhDaiDien')" >Chọn Hình</button>
                        <?php
                        FormSanPham::UrlImages($_item->UrlImages)->render();
                        ?>
                    </label>
                </div>
            </div>
            <div class="box-footer" >

            </div>
        </div>    
    </form>    
</div>
