<ol class="breadcrumb" >
    <li><a href="/backend" >Dashboard</a></li>
    <li> Công Ty</li>
</ol>

<div class="container-fluid" >
    <form method="get" action="">
        <div class="form-group d-flex" >

        </div>
    </form>
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Công Ty</h3>
            <div class="box-tools" >
                <a href="/options/post/congty/" class="btn btn-primary" ><i class="fa fa-plus" ></i></a>
            </div>
        </div>
        <div class="box-body" >
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th>STT</th>
                        <th>Mã </th>
                        <th>Tên</th>
                        <th>Cấp Trực Thuộc</th>
                        <th>Ẩn Hiện</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ($Items) {
                        foreach ($Items as $k => $item) {
                            $_item = new Model\Locations($item);
                            ?>
                            <tr>
                                <th><?php echo $k + 1 ?></th>
                                <th><?php echo $_item->Id ?></th>
                                <th><?php echo $_item->Name ?></th>
                                <th><?php echo $_item->Parents()->Name ?></th>
                                <th><?php echo $_item->IsPublic ?></th>
                            </tr>

                            <?php
                        }
                    }
                    ?>
                </tbody>
            </table>
        </div>
        <div class="box-footer" >
            <div  class="d-flex">
                <?php
                \Model\FormCommon::Select("", "", [10, 20, 50, 100], [
                    "style" => "max-width:150px;",
                    "class" => "form-control",
                    "value" => $pageNumber,
                    "onchange" => "SoDongHienThi(this.value)",
                        ]
                )->render();
                ?>
                <?php
                $linkPhanTrang = "/locations/index/?keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" >
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/locations/index/?keyword=&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>


