<ol class="breadcrumb" >
    <li><a href="/index.php?controller=backend" >Home</a></li>
    <li> Quản Lý Tài Khoản </li>
</ol> 
<div class="container-fluid" >
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Danh Sách Tài Khoản</h3>
            <div class="box-tools" >
                <?php
                echo Model\User::btnThem();
                ?>
                
            </div>
        </div>
        <div class="box-body" >
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th>STT</th>
                        <th>Tài Khoản</th>
                        <th>Họ & Tên</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($DanhSachTaiKhoan as $index => $user) {
                        $_user = new Model\User($user);
                        ?> 
                        <tr>
                            <th> 

                                <?php
                                echo $_user->btnSua();
                                echo $_user->btnXoa();
                                ?>
                            </th>
                            <th><?php echo $index + 1; ?></th>
                            <th><?php echo $_user->Username; ?></th>
                            <th><?php echo $_user->Name; ?></th>
                            <th><?php echo $_user->Email; ?></th>
                        </tr>
                        <?php
                    }
                    ?> 
                </tbody>
            </table>        
        </div>

    </div>    
</div>

