<ol class="breadcrumb" >
    <li><a href="/index.php?controller=backend" >Home</a></li>
    <li><a href="/index.php?controller=quanlyusers" >Quản Lý Tài Khoản</a></li>
    <li> Thêm </li>
</ol>
<?php
$roleDetail = new Model\Role();
?>
<div class="container-fluid" >
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Tạo Tài Khoản</h3>
            <div class="box-tools" >
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <div class="box-body" >
            <form action="" method="POST">
                <div class="row" >
                    <div class="col-md-6" >
                        <?php
                        \Model\Users\FormUser::Name()->renderHTML();
                        \Model\Users\FormUser::Username()->renderHTML();
                        \Model\Users\FormUser::Email()->renderHTML();

                        \Model\Users\FormUser::Active()->renderHTML();
                        ?> 

                        <div class="form-group" >
                            <label>Mật Khẩu</label>
                            <div class="d-flex" >
                                <?php
                                \Model\Users\FormUser::CreatePassword()->render();
                                ?>
                                <button type="button" data-target="#CreatePassword"  class="btngeneratePassword btn btn-primary" >Ngâu Nhiên</button>
                            </div>
                        </div>
                        <div class="form-group " >  
                            <button class="btn btn-default"  type="reset" >Làm Lại</button>
                            <button class="btn btn-success" >Lưu</button>
                            <button class="btn btn-success" name="LuuThoat" >Lưu & Thoát</button>
                        </div>

                    </div>
                </div>
            </form>
        </div>
    </div>


</div>