<ol class="breadcrumb" >
    <li><a href="/index.php?controller=backend" >Home</a></li>
    <li><a href="/index.php?controller=quanlyusers" >Quản Lý Tài Khoản</a></li>
    <li> Sửa </li>
</ol>
<?php
//var_dump($user);
$modelUser = new Model\User($user);
//var_dump($modelUser);
?>
<div class="container-fluid" >
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Tạo Tài Khoản</h3>
            <div class="box-tools" >
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <div class="box-body" >
            <div class="row" >
                <div class="col-md-6" >
                    <form action="" method="POST">
                        <?php
                        \Model\Users\FormUser::Name($modelUser->Name)->renderHTML();
                        \Model\Users\FormUser::Username($modelUser->Username)->renderHTML();
                        \Model\Users\FormUser::Email($modelUser->Email)->renderHTML();
                        \Model\Users\FormUser::Active($modelUser->Active)->renderHTML();
                        ?> 


                        <div class="form-group " >  
                            <button class="btn btn-default"  type="reset" >Làm Lại</button>
                            <button class="btn btn-success" >Lưu</button>
                            <button class="btn btn-success" name="LuuThoat" >Lưu & Thoát</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-6" >
                    <form action="">
                        <div class="box box-primary" >
                            <div class="box-header" >
                                <h3 class="box-title" >Reset Mật Khẩu</h3> 
                            </div>
                            <div class="box-body" >
                                <div class="form-group" >
                                    <label>Mật Khẩu</label>
                                    <div class="d-flex" >
                                        <?php
                                        \Model\Users\FormUser::CreatePassword()->render();
                                        ?>
                                        <button type="button" data-target="#CreatePassword"  class="btngeneratePassword btn btn-primary" >Ngâu Nhiên</button>
                                    </div>
                                </div>


                            </div>
                            <div class="box-footer" >
                                <button class="btn btn-success" >Lưu</button>
                            </div>
                        </div>
                    </form>
                    <div class="box box-primary" >
                        <div class="box-header" >
                            <h3 class="box-title" >Danh Sách Quyền</h3> 
                        </div>
                        <div class="box-body" >
                            <?php
                            $modelRole = new Model\Role();
                            $total = 0;
                            $roles = $modelRole->GetItems(["keyword" => ""], 1, 1000, $total);
                            foreach ($roles as $role) {
                                $_role = new Model\Role($role);
                                ?> 
                                <div class="list-group" >
                                    <div><label><input type="checkbox" name="Roles[<?php echo $_role->Id ?>]" >  <?php echo $_role->Name ?> </label> </div>
                                </div>
                                <?php
                            }
                            ?>



                        </div>
                        <div class="box-footer" >
                            <button class="btn btn-success" >Lưu</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


</div>