<?php

use Module\baiviet\Model\DuAn\FormDuAn;

$_item = new \Module\baiviet\Model\DuAn\DuAn($Item);
?>
<ol class="breadcrumb" >
    <li><a href="/backend" >Home</a></li>
    <li><a href="/baiviet/duan/" >Quản Lý Dự Án</a></li>
    <li> Sửa Dự Án </li>
</ol>
<div  class="container-fluid" >
    <form action="" method="post">
        <div class="box box-primary" >
            <div class="box-header" >
                <h3 class="box-title" >Thêm Mới</h3>  
            </div>
            <div class="box-body" >
                <div class="col-md-3" >
                    <?php
                    FormDuAn::Id($_item->Id)->renderHTML();
                    FormDuAn::Name($_item->Name)->renderHTML();
                    FormDuAn::Alias($_item->Alias)->renderHTML();
                    FormDuAn::Tinh($_item->Tinh)->renderHTML();
                    FormDuAn::Huyen($_item->Huyen,$_item->Tinh)->renderHTML();
//                    FormDuAn::Xa($_item->Xa)->renderHTML();
                    FormDuAn::DiaChi($_item->DiaChi)->renderHTML();
                    ?>   
                </div>
                <div class="col-md-9" >
                    <div class="row" >
                        <div role="tabpanel">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#Images" aria-controls="Images" role="tab" data-toggle="tab"> Hình Ảnh </a>
                                </li>
                                <li role="presentation" class="active">
                                    <a href="#home" aria-controls="home" role="tab" data-toggle="tab">Mô Tả</a>
                                </li>
                                <li role="presentation">
                                    <a href="#tab" aria-controls="tab" role="tab" data-toggle="tab">Nội Dung</a>
                                </li>
                                <li role="presentation">
                                    <a href="#seo" aria-controls="seo" role="tab" data-toggle="tab">SEO</a>
                                </li>
                            </ul> 
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane  " id="Images">
                                    <img src="<?php echo $_item->Images; ?>" style="height: 100px;" id="thumbnailsImages" >
                                    <?php
                                    FormDuAn::Images($_item->Images)->render();
                                    ?>
                                    <button type="button" onclick="BrowseServer('UrlImages','thumbnailsImages')" >Chọn hình</button>
                                </div>
                                <div role="tabpanel" class="tab-pane  " id="home">
                                    <?php
                                    FormDuAn::Sumary($_item->Sumary())->renderHTML();
                                    ?>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="seo">
                                    <?php
                                    FormDuAn::Des($_item->Des)->renderHTML();
                                    FormDuAn::Title($_item->Title)->renderHTML();
                                    FormDuAn::Keyword($_item->Keyword)->renderHTML();
                                    ?>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="tab">
                                    <?php
                                    FormDuAn::Content($_item->Content())->renderHTML();
                                    ?>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>   
            </div>
            <div class="box-footer" >
                <input type="submit" class="btn btn-success" name="Luu" value="Lưu" />
            </div>
        </div>    
    </form>    
</div>


