<ol class="breadcrumb" >
    <li><a href="/backend" >Trang chủ</a></li>
    <li>Đơn Hàng</li>
</ol>
<div class="container-fluid" >
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Danh sách đơn hàng</h3>
            <div class="box-tools" >
                <a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>
            </div>
        </div>
        <div class="box-body" >

        </div>
    </div>
    
</div>