<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Home | E-Shopper</title>
        <link href="/public/eshopper/css/bootstrap.min.css" rel="stylesheet">
        <link href="/public/eshopper/css/font-awesome.min.css" rel="stylesheet">
        <link href="/public/eshopper/css/prettyPhoto.css" rel="stylesheet">
        <link href="/public/eshopper/css/price-range.css" rel="stylesheet">
        <link href="/public/eshopper/css/animate.css" rel="stylesheet">
        <link href="/public/eshopper/css/main.css" rel="stylesheet">
        <link href="/public/eshopper/css/responsive.css" rel="stylesheet"> 
        <link rel="shortcut icon" href="/public/eshopper/images/ico/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/public/eshopper/images/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/public/eshopper/images/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/public/eshopper/images/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/public/eshopper/images/ico/apple-touch-icon-57-precomposed.png">
        <script src="/public/eshopper/js/jquery.js"></script>
<!--        <script type="application/ld+json"> 
            { "@context": "https://schema.org/", "@type": "CreativeWorkSeries", "name": "Chất liệu PP là gì? Ưu - nhược điểm và ứng dụng của PP", "aggregateRating": { "@type": "AggregateRating", "ratingValue": "5", "bestRating": "5", "ratingCount": "1000" } }
                </script>-->
    </head><!--/head-->

    <body>

        <?php
        echo \Views\theme\eshopper\Functions::Header();
        echo \Views\theme\eshopper\Functions::Slider();
        ?>
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="left-sidebar">
                            <h2>Category</h2>


                            <div class="panel-group category-products" id="accordian1"><!--category-productsr-->
                                <?php
                                $dm = new Module\quanlysanpham\Model\DanhMuc();
                                $dsDM = $dm->DanhMucTheoCapCha("");
                                foreach ($dsDM as $key => $value) {
                                    $_dm = new Module\quanlysanpham\Model\DanhMuc($value);
                                    $dmCon = $dm->DanhMucTheoCapCha($_dm->Id);
                                    if ($dmCon) {
                                        ?> 
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a data-toggle="collapse" data-parent="#accordian1" href="#sportswear<?php echo $key; ?>">
                                                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                                        <?php echo $_dm->Name; ?>
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="sportswear<?php echo $key; ?>" class="panel-collapse collapse">
                                                <div class="panel-body">
                                                    <ul>
                                                        <?php
                                                        foreach ($dmCon as $key => $value) {
                                                            $dmConitem = new Module\quanlysanpham\Model\DanhMuc($value);
                                                            ?> 
                                                            <li><a href="<?php echo $dmConitem->Link(); ?>"><?php echo $dmConitem->Name; ?> </a></li>
                                                            <?php
                                                        }
                                                        ?>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <?php
                                    } else {
                                        ?> 
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title"><a href="#"><?php echo $_dm->Name ?></a></h4>
                                            </div>
                                        </div>
                                        <?php
                                    }
                                }
                                ?>







                            </div><!--/category-products-->

                            <div class="brands_products"><!--brands_products-->
                                <h2>Thương Hiệu</h2>
                                <?php
                                $ops = new Model\OptionsService();
                                $items = $ops->GetGroupsId("thuonghieu");
                                ?>
                                <div class="brands-name">
                                    <ul class="nav nav-pills nav-stacked">
                                        <?php
                                        foreach ($items as $key => $value) {
                                            $_ops = new Model\OptionsService($value["Id"]);
                                            ?> 
                                            <li><a href="/thuong-hieu/<?php echo $_ops->Val; ?>.html"> <span class="pull-right">  </span><?php echo $_ops->Val; ?></a></li>
                                            <?php
                                        }
                                        ?>
                                    </ul>
                                </div>
                            </div><!--/brands_products-->

                            <div class="price-range"><!--price-range-->
                                <h2>Price Range</h2>
                                <div class="well text-center">
                                    <?php
                                    $giaTu = isset($_REQUEST["giatu"]) ? intval($_REQUEST["giatu"]) : 200000;
                                    $giaDen = isset($_REQUEST["giaden"]) ? intval($_REQUEST["giaden"]) : 500000;
                                    ?>
                                    <input type="text" class="span2" value="" data-slider-min="100000" data-slider-max="1000000" data-slider-step="50000" data-slider-value="[<?php echo $giaTu ?>,<?php echo $giaDen ?>]" id="sl2" >
                                    <br />
                                    <b class="pull-left">100.000</b> <b class="pull-right">1.000.000</b>
                                </div>
                            </div><!--/price-range-->

                            <div data-url="/ajaxhtml/shippingImg/" data-target="#shippingImg" id="shippingImg" class="ajaxHtml shipping text-center"><!--shipping-->
                                
                            </div>

                        </div>
                    </div>

                    <div class="col-sm-9 padding-right">
                        <?php
                        include $_Content;
                        ?>

                    </div>
                </div>
            </div>
        </section>

        <?php
        echo \Views\theme\eshopper\Functions::Footer();
        ?>



        <script src="/public/eshopper/js/jquery.js"></script>
        <script src="/public/eshopper/js/bootstrap.min.js"></script>
        <script src="/public/eshopper/js/jquery.scrollUp.min.js"></script>
        <script src="/public/eshopper/js/price-range.js"></script>
        <script src="/public/eshopper/js/jquery.prettyPhoto.js"></script>
        <script src="/public/eshopper/js/main.js"></script>
        <script src="/public/eshopper/App.js" type="text/javascript"></script>
        <script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=61d8351cfa9c81001d245630&product=sop' async='async'></script>
    </body>
</html>