<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Home | E-Shopper</title>
        <link href="/public/eshopper/css/bootstrap.min.css" rel="stylesheet">
        <link href="/public/eshopper/css/font-awesome.min.css" rel="stylesheet">
        <link href="/public/eshopper/css/prettyPhoto.css" rel="stylesheet">
        <link href="/public/eshopper/css/price-range.css" rel="stylesheet">
        <link href="/public/eshopper/css/animate.css" rel="stylesheet">
        <link href="/public/eshopper/css/main.css" rel="stylesheet">
        <link href="/public/eshopper/css/responsive.css" rel="stylesheet"> 
        <link rel="shortcut icon" href="/public/eshopper/images/ico/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/public/eshopper/images/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/public/eshopper/images/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/public/eshopper/images/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/public/eshopper/images/ico/apple-touch-icon-57-precomposed.png">
    </head><!--/head-->

    <body>

        <?php
        echo \Views\theme\eshopper\Functions::Header();
        ?>
        <section id="cart_items">
            <div class="container">
                <div class="breadcrumbs">
                    <ol class="breadcrumb">
                        <li><a href="#">Home</a></li>
                        <li class="active">Shopping Cart</li>
                    </ol>
                </div>
                <?php
                include $_Content;
                ?>
            </div>
        </section>

        <?php
        echo \Views\theme\eshopper\Functions::Footer();
        ?>



        <script src="/public/eshopper/js/jquery.js"></script>
        <script src="/public/eshopper/js/bootstrap.min.js"></script>
        <script src="/public/eshopper/js/jquery.scrollUp.min.js"></script>
        <script src="/public/eshopper/js/price-range.js"></script>
        <script src="/public/eshopper/js/jquery.prettyPhoto.js"></script>
        <script src="/public/eshopper/js/main.js"></script>
        <script src="/public/eshopper/App.js" type="text/javascript"></script>
    </body>
</html>