<?php
$error = \Model\Error::GetError();
if ($error != null) {
    ?> 
    <div class="alert alert-<?php echo $error["Type"]; ?> alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <?php echo $error["Content"]; ?>
    </div>
    <?php
} 
$isCheck = isset($_COOKIE["GhiNhoMatKhau"]) ? "checked" : "";
$taiKhoan = isset($_COOKIE["TaiKhoan"]) ? $_COOKIE["TaiKhoan"] : "";
?>

<form action="" method="post">
    <div class="form-group has-feedback">
        <input type="text" value="<?php echo $taiKhoan; ?>" required="required" name="TaiKhoan" class="form-control" placeholder="tài khoản">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
        <input type="password" required="required" name="MatKhau" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>
    <div class="row">
        <div class="col-xs-8">
            <div class="checkbox icheck">
                <label>
                    <input <?php echo $isCheck; ?> type="checkbox" name="GhiNhoMatKhau" value="1" > Ghi Nhớ Mật Khẩu
                </label>
            </div>
        </div><!-- /.col -->
        <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Đăng Nhập</button>
        </div><!-- /.col -->
    </div>
</form>

<div class="social-auth-links text-center">
    <p>- Hoặc -</p>
    <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
    <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
</div><!-- /.social-auth-links -->

<a href="#">Quyên Mật Khẩu</a><br> 