<ol class="breadcrumb" >
    <li><a href="/index.php?controller=backend" >Home</a></li>
    <li><a href="/index.php?controller=quanlyusers" >Quản Lý Tài Khoản</a></li>
    <li> Sửa </li>
</ol>
<?php
//var_dump($user);
$modelUser = Model\User::CurentUser();
//var_dump($modelUser);
?>
<div class="container-fluid" >
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Thông Tin Chung</h3>
            <div class="box-tools" >
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <div class="box-body" >
            <div class="row" >
                <div class="col-md-6" >
                    <form action="" method="POST">
                        <?php
                        \Model\Users\FormUser::Id($modelUser->Id)->render();
                        \Model\Users\FormUser::Username($modelUser->Username)->renderHTML();
                        \Model\Users\FormUser::Name($modelUser->Name)->renderHTML();
                        \Model\Users\FormUser::Email($modelUser->Email)->renderHTML();
                        \Model\Users\FormUser::BOD($modelUser->BODFomatDB())->renderHTML();
                        ?>  
                        <div class="form-group " >  
                            <button class="btn btn-default"  type="reset" >Làm Lại</button>
                            <button class="btn btn-success" >Lưu</button>
                            <button class="btn btn-success" name="LuuThoat" >Lưu & Thoát</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-6" >
                    <form method="POST" action="">
                        <div class="box box-primary" >
                            <div class="box-header" >
                                <h3 class="box-title" >Bảo Mật</h3> 
                            </div>
                            <div class="box-body" >
                                <div class="form-group" > 
                                    <div class="form-group" >
                                        <label>Mật Khẩu Cũ</label>
                                        <input class="form-control" name="Password" value="" type="password"  >
                                    </div>
                                    <div class="form-group" >
                                        <label>Mật Khẩu Mới</label>
                                        <input class="form-control" name="NewPassword" value="" type="password"  >
                                    </div>
                                    <div class="form-group" >
                                        <label>Nhập Lại Mật Khẩu</label>
                                        <input class="form-control" name="RePassword" value="" type="password"  >
                                    </div>
                                     
                                </div> 
                            </div>
                            <div class="box-footer" >
                                <button class="btn btn-success" >Lưu</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>


</div>