<?php 
//var_dump($DanhMuc);
?>
<div class="features_items"> 
    <h2 class="title text-center"><?php echo $DanhMuc->Name ?></h2>
    <?php
    
    if ($Items) {
        foreach ($Items as $key => $sanpham) {
            $_item = new Module\quanlysanpham\Model\SanPham($sanpham);
            ?> 
            <div class="col-sm-4">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="<?php echo $_item->UrlImages; ?>" alt="<?php echo $_item->Name; ?>" />
                            <h2><?php echo $_item->Price(); ?></h2>
                            <p>
                                <a href="<?php echo $_item->LinkChiTiet(); ?>" ><?php echo $_item->Name; ?></a></p>
                            <a href="<?php echo Module\cart\Model\Cart::LinkThemSanPham($_item->Id); ?>" class="btn btn-default add-to-cart">
                                <i class="fa fa-shopping-cart"></i>Thêm Giỏ Hàng
                            </a>
                        </div>
                        <div class="product-overlay">
                            <div class="overlay-content">
                                <h2><?php echo $_item->Price(); ?></h2>
                                <p>
                                    <a href="<?php echo $_item->LinkChiTiet(); ?>" ><?php echo $_item->Name; ?></a>
                                </p>

                                <a href="<?php echo Module\cart\Model\Cart::LinkThemSanPham($_item->Id); ?>" class="btn btn-default add-to-cart">
                                    <i class="fa fa-shopping-cart"></i>Thêm Giỏ Hàng
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="choose">
                        <ul class="nav nav-pills nav-justified">
                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <?php
        }
    }
    ?> 
</div><!--features_items-->
 
<?php 
$LinkPhanTrang = "[i]"; 
echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $LinkPhanTrang);
?>