<div class="features_items"> 
    <h2 class="title text-center">Features Items</h2>
    <?php
    $SanPham = new Module\quanlysanpham\Model\SanPham();
    $items = $SanPham->SanPhamMoi(6);
    if ($items) {
        foreach ($items as $key => $sanpham) {
            $_item = new Module\quanlysanpham\Model\SanPham($sanpham);
            ?> 
            <div class="col-sm-4">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="<?php echo $_item->UrlImages; ?>" alt="<?php echo $_item->Name; ?>" />
                            <h2><?php echo $_item->Price(); ?></h2>
                            <p>
                                <a href="<?php echo $_item->LinkChiTiet(); ?>" ><?php echo $_item->Name; ?></a></p>
                            <a href="<?php echo Module\cart\Model\Cart::LinkThemSanPham($_item->Id); ?>" class="btn btn-default add-to-cart">
                                <i class="fa fa-shopping-cart"></i>Thêm Giỏ Hàng
                            </a>
                        </div>
                        <div class="product-overlay">
                            <div class="overlay-content">
                                <h2><?php echo $_item->Price(); ?></h2>
                                <p>
                                    <a href="<?php echo $_item->LinkChiTiet(); ?>" ><?php echo $_item->Name; ?></a>
                                </p>

                                <a href="<?php echo Module\cart\Model\Cart::LinkThemSanPham($_item->Id); ?>" class="btn btn-default add-to-cart">
                                    <i class="fa fa-shopping-cart"></i>Thêm Giỏ Hàng
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="choose">
                        <ul class="nav nav-pills nav-justified">
                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <?php
        }
    }
    ?>


</div><!--features_items-->

<div class="category-tab"><!--category-tab-->
    <div class="col-sm-12">
        <ul class="nav nav-tabs">
            <?php
            $danhMuc = new Module\quanlysanpham\Model\DanhMuc();
            $total = 0;
            $itemDM = $danhMuc->GetItems(["keyword"=>""], 1, 10, $total);
            foreach ($itemDM as $key => $value) {
                $_Dm = new Module\quanlysanpham\Model\DanhMuc($value);
                ?> 
                <li class="<?php echo $key == 0 ? 'active' : '' ?>"><a href="#<?php echo $_Dm->Id ?>" data-toggle="tab"><?php echo $_Dm->Name ?></a></li>
                <?php
            }
            ?>

        </ul>
    </div>
    <div class="tab-content">
        <?php
        foreach ($itemDM as $key => $value) {
            $_Dm = new Module\quanlysanpham\Model\DanhMuc($value);
            ?> 
            <div data-url="/ajaxhtml/danhsachsanphamtheodanhmuc/<?php echo $_Dm->Id ?>"  
                 data-target="#<?php echo $_Dm->Id ?>"  class="tab-pane <?php echo $key == 0 ? 'active' : '' ?> ajaxHtml fade in" id="<?php echo $_Dm->Id ?>" >
            </div>
            <?php
        }
        ?> 
    </div>
</div><!--/category-tab-->

<div class="recommended_items ajaxHtml"  data-url="/ajaxhtml/recommended/" data-target="#recommendeditems" id="recommendeditems"  ><!--recommended_items-->
    
</div> 