<?php 
$item = new \Module\baiviet\Model\Pages\PagesService($Item);
?>
<div class="blog-post-area">
    <h2 class="title text-center"><?php echo $item->Name; ?></h2>
    <div class="single-blog-post"> 
        <div class="post-meta"> 
            <span>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-half-o"></i>
            </span>
        </div>
        
        <?php 
        echo $item->Content();
        ?>
        
        
    </div>
</div>