<ol class="breadcrumb" >
    <li><a href="/backend" >Home</a></li>
    <li> Danh Sách Banner Động</li>
</ol>
<div class="container-fluid" >
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Danh Mục Sản Phẩm</h3>
            <div class="box-tools" >
                

            </div>
        </div>
        <div class="box-body" >
            <table class="table table-bordered">
                
            </table> 

        </div>
    </div>    
</div>    