<?php

use Module\giaodien\Model\Slide\SliderService;
use Module\giaodien\Model\Slide\FormSlider;

$_item = new SliderService($Item);
?>
<ol class="breadcrumb" >
    <li><a href="/backend" >Home</a></li>
    <li><a href="/giaodien/slider/" >Danh Sách Banner Động</a> </li>
    <li> Sửa</li>
</ol>
<div class="container-fluid" >
    <div class=" " >
        <form action="" method="POST" >
            <div class="box box-primary" >
                <div class="box-header" >
                    <h3 class="box-title" >Sửa Slide</h3>
                    <div class="box-tools" >    

                    </div>
                </div>
                <div class="box-body" >

                    <div class="row" >

                    </div>
                    <div class="row" >
                        <div class="col-md-4" >
                            <?php FormSlider::Id($_item->Id)->renderHTML(); ?> 
                            <?php FormSlider::Name($_item->Name)->renderHTML(); ?> 
                            <?php FormSlider::GroupsId($_item->GroupsId)->renderHTML(); ?> 
                            <?php FormSlider::IsPublic($_item->IsPublic)->renderHTML(); ?> 

                            <img id="imgHinhChinh" class="img  img-responsive" src="<?php echo $_item->Images; ?>" > 
                            <div class="form-group" >
                                <label>Hình</label>
                                <div class="d-flex" >
                                    <?php
                                    FormSlider::Images($_item->Images)->render();
                                    ?>
                                    <button class="btn btn-primary" type="button" onclick="BrowseServer('Input_Images', 'imgHinhChinh')" >Chọn Hình</button>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8" ><?php FormSlider::Content($_item->Content())->renderHTML(); ?></div>
                    </div>


                </div>
                <div class="box-footer" >
                    <button class="btn btn-success" >Save</button>
                </div>
            </div>
        </form>
    </div>

</div>
