<ol class="breadcrumb" >
    <li><a href="/index.php?controller=backend" >Home</a></li>
    <li> Danh Sách Quyền </li>
</ol>
    

 <div class="container-fluid" >
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Danh Sách Quyền</h3>
            <div class="box-tools" >
                <?php 
                 echo \Model\Role::btnThem();
                ?>
                
            </div>
        </div>
        <div class="box-body" >
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th>STT</th>
                        <th>Mã Quền</th>
                        <th>Tên Quền</th>
                        <th>Mô Tả</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($DanhSachRole as $index => $role) {
                        $_role = new Model\Role($role);
                        ?> 
                        <tr>
                            <th> 
                                
                                <?php
                                echo $_role->btnSua();
                                echo $_role->btnXoa();
                                ?>
                            </th>
                            <th><?php echo $index + 1; ?></th>
                            <th><?php echo $_role->Id; ?></th>
                            <th><?php echo $_role->Name; ?></th>
                            <th><?php echo $_role->Des; ?></th>
                        </tr>
                        <?php
                    }
                    ?> 
                </tbody>
            </table>        
        </div>

    </div>    
</div>

